Update DevOps_Pipeline_Simon.yml

diff --git a/.github/workflows/DevOps_Pipeline_Simon.yml b/.github/workflows/DevOps_Pipeline_Simon.yml
--- a/.github/workflows/DevOps_Pipeline_Simon.yml
+++ b/.github/workflows/DevOps_Pipeline_Simon.yml
@@ -40,8 +40,12 @@ jobs:
    
     - name: Test with pytest
       run: |
-        pytest > error_log.txt
-        cat error_log.txt
+       pytest >  error_log.txt 2>&1
+          if [ $? -ne 0 ]; then
+            echo "Tests failed. See pytest_output.txt for details."
+            cat  error_log.txt
+            exit 1
+          fi
       continue-on-error: true
      
       if: failure() && ${{inputs.run_test_job == 'true'}}
